### ISSUE TITLE
In batch mode consumer, when constructing a List with a mix of original types and KafkaNull, the original type data disappears.

### ISSUE THREAD

**Issue by miki1029** [spring-cloud/spring-cloud-function#1019]
**Describe the bug**

* jdk : temurin-17
* kotlin : 1.7.21
* spring boot : 3.0.2
* spring cloud : 2022.0.1
* spring-cloud-function-context : 4.0.1

I use a batch consumer of type `Consumer<List<Envelope>>` using spring cloud stream.

And I use Kafka, and in Kafka a **tombstone** event may be generated. This is being treated as a `KafkaNull` in spring.

Since the consumer is in **batch mode**, the parameters have a **mix of Envelope and KafkaNull in one List**, and this is where the problem arises.

**SimpleFunctionRegistry.java**
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/4443853/229012253-ddfe7ef2-3686-4b56-a20f-0ca669764537.png">

If all the types were `Envelope`, line 1289 would be `true` and the payload would be used as is, but since it's now mixed with `KafkaNull`, the `collectionType` is determined to be `null`, making line 1289 `false`. Then, on line 1300 below, the convert logic is executed.

**SmartCompositeMessageConverter.java**
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/4443853/229012706-77e1f07e-69ba-49b5-9f4e-117cdc5e4a7e.png">

This is where the problem arises. The `KafkaNull` was replaced with `null` just fine on line 91, but the `Envelope` is not included in the `resultList` because **there is no converter that can handle the Envelope type** (even though there is no need to convert it).

I've attached the `iterablePayload`, `resultList`, below to the Sample (at line 109)
In `resultList`, all 7 elements are null, which means that out of 27 data in `iterablePayload`, only 7 data that are `KafkaNull` were converted to `null` and included in `resultList`, and **remaining 20 data that are `Envelope` type were discarded.**

**I believe that the 20 data of type `Envelope` were also included in the List, so that the `resultList` should have a total of 27 elements. I am assuming that this is a bug.**

And I think it would be nice to at least leave an error log for elements that didn't convert.

**Sample**
<img width="877" alt="image" src="https://user-images.githubusercontent.com/4443853/229013649-a786f747-9479-4368-9473-64ac71fa4aa8.png">

<img width="304" alt="image" src="https://user-images.githubusercontent.com/4443853/229013665-08922bea-458e-46a1-aab4-43a957fb00fa.png">

```yaml
spring:
  cloud:
    stream:
      default-binder: kafka
    function:
      definition: myStream

spring.cloud.stream.bindings:
  myStream-in-0:
    destination: ${my-destination}
    group: ${my-group}
    content-type: application/*+avro
    consumer:
      batch-mode: true

spring.cloud.stream.kafka.bindings:
  myStream-in-0:
    consumer:
      start-offset: earliest
      common-error-handler-bean-name: commonErrorHandler
      configuration:
        key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: ${my-url}
        specific.avro.reader: true

        max.poll.records: 100
        fetch.min.bytes: 1
        fetch.max.wait.ms: 300000
        max.poll.interval.ms: 360000
        request.timeout.ms: 360000
```

```kotlin
@Configuration
class MyStreamConfig {
    @Bean
    fun myStream(): Consumer<List<Envelope?>> {
        return Consumer<List<Envelope?>> { list ->
            // my logic
        }
    }
}
```
