### ISSUE TITLE
"output-header-mapping-expression" is not working for streamBridge

### ISSUE THREAD

**Issue by GreenRover** [spring-cloud/spring-cloud-function#1044]
**Describe the bug**
The configuration `output-header-mapping-expression` not longer working with streamBridge in spring cloud version `2022.0.3` | spring cloud function 4.0.3

Original feature request: #676

**Sample**
Sample java code:
```java
        Message<SensorReading> message = MessageBuilder
                .withPayload(reading)
                .setHeader(
                        BinderHeaders.TARGET_DESTINATION,
                        baseDestination + "/" + location)
                .build();
        streamBridge.send("emitTemperatureSensorDynamic-out-0", message);
```

Sample configuration:
```yaml
spring:
  cloud:
    function:
      configuration:
        emitTemperatureSensorDynamic:
          output-header-mapping-expression:
            solace_timeToLive: 23000L
            solace_senderId: @project.artifactId@_${HOSTNAME}
    stream:
      bindings:
        emitTemperatureSensorDynamic-out-0:
          contentType: "application/json"
          binder: solace
```

is not working because there is no function/bean for `emitTemperatureSensorDynamic`
![Snag_6105cb9](https://github.com/spring-cloud/spring-cloud-function/assets/512850/5da32c52-f23e-4631-8e22-3e5f8a6d26b3)

with this configuration, messages will send out but without add the expected headers.

**History**

In older version it was possible to use the _not perfect_ solution:
```yaml
spring:
  cloud:
    function:
      configuration:
        streamBridge:
          output-header-mapping-expression:
            solace_timeToLive: 23000L
            solace_senderId: @project.artifactId@_${HOSTNAME}
```

This now raise the exception:
```
2023-06-01T14:38:25.602+0200 ERROR Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot load from object array because "contentType" is null] with root cause
java.lang.NullPointerException: Cannot load from object array because "contentType" is null
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertOutputIfNecessary(SimpleFunctionRegistry.java:1170) ~[spring-cloud-function-context-4.0.2.jar:4.0.2]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:708) ~[spring-cloud-function-context-4.0.2.jar:4.0.2]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvo
```

This solution was not perfect because there was just a single setting for messages send out via StreamBridge. But in bigger applications a configuration per binding would be required. An additional global "default configuration" would be a nice to have.

**Expected**
The configuration
```yaml
spring:
  cloud:
    function:
      configuration:
        emitTemperatureSensorDynamic:
          output-header-mapping-expression:
            solace_timeToLive: 23000L
            solace_senderId: @project.artifactId@_${HOSTNAME}
```
 would add the wanted header to messages when sending messages via
 ```java
        Message<SensorReading> message = MessageBuilder.withPayload(reading).build();
        streamBridge.send("emitTemperatureSensorDynamic-out-0", message);
```

**Comment by Mrc0113** [comment]
thanks @GreenRover. I agree your `Expected` outcome would be useful as it would allow for multiple header mapping configurations that a dev can choose from when publishing to dynamic topics AND also keep that header info in the Spring config. 

FYI @olegz

**Comment by olegz** [comment]
Something must be missing from your explanation as I can't reproduce it. The StreamBridge is registered under function named `streamBridge`, so I have no idea how and why do you have lookup performed for `emitTemperatureSensorDynamic`. 

Perhaps a failing test case as a PR or a reproducible sample?

**Comment by olegz** [comment]
Also, StreamBridge is not part of the Spring Cloud Function. In other words SCF has no idea of what StreamBridge is, so why did you expect it to work in the first place? Sure it worked for `streamBridge` because there is a function name registered under that name, but `emitTemperatureSensorDynamic` is just a dynamic destination you're sending a message to;  using a framework that has no knowledge of s-c-stream or stream bridge. .. 
So I am confused

**Comment by GreenRover** [comment]
@olegz I provided you a reproducer: https://github.com/GreenRover/reproducer1044
Just run both test to so the effects

**Comment by GreenRover** [comment]
Thank you oleg,

the business use case is:
- being able to set header by configuration when messages sen out using streamBridge
- configure solace senderId via configuration (for all bindings)
- configure message ttl via solace header per binding

I am aware that i could achieve this with @Config annotation. But this would make code less readable

**Comment by olegz** [comment]
How do you envision this:  `set header by configuration when messages sen out using streamBridge`??
`StreamBridge` is effectively a routing component used to send data to multiple destinations. Some of these destinations configured explicitly and some not. But regardless, `StreamBridge` is just a sender, very similar to `*Template` classes in Spring (i.,e. JMSTemplate, JdbcTemplate etc).

You can certainly send instance of Message via StreamBridge and set all the headers you want. You can also configure the output bindings, but, just to reiterate. . .
```
spring:
  cloud:
    function:
      configuration:
        streamBridge:
          output-header-mapping-expression:
```
The above implies that you are configuring `streamBridge` function. Which is correct. But this also means that the same `output-header-mapping-expression` and other configurations will be used for ALL destination you are sending to using streamBridge.

I am not sure what else I can add here. In any event, StreamBridge is a component of s-c-stream, so i'll resolve this issue with no action, but if you have more ideas or specifics feel free to open a new one in s-c-stream and link this issues.
