### ISSUE TITLE
Aws API Gateway support (AwsProxyRequest, AwsProxyResponse)?

### ISSUE THREAD

**Issue by fredoche** [spring-cloud/spring-cloud-function#111]
Everything in this issue relates to AWS Lambda with API Gateway.
According to the documentation, Functions are auto-detected and applied to input by the SpringBootStreamHandler of SpringBootRequestHandler.
I have found that, for my usage, the stream version of the lambda handler is more flexible, with Api gateway integration type set to "proxy".
However, the input stream won't be mappable to a "business" type (Foo.class in your examples) but to an AwsProxyRequest (structure described [there](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/AwsProxyRequest.java) , and in turn API gateway expects an AwsProxyResponse in the output stream.

It it expected to create Function<AwsProxyRequest, AwsProxyResponse>, which is broad and maybe too generic, or is there already a way to transparently map this api gateway interface in spring-cloud-functions ?

**Comment by khalidx** [comment]
How are folks deploying Lambdas with events from API Gateway today? I'm using the CloudFormation SAM configuration below and can't seem to get it wired correctly.

```
  Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: aws.Handler
      Runtime: java8
      CodeUri: './target/app.jar'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
```
