### ISSUE TITLE
Function local invocation 

### ISSUE THREAD

**Issue by VSVDEv** [spring-cloud/spring-cloud-function#1209]
**Describe the bug**
When I download example https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws 

I want to use it without http, so I updated template.yaml

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example function as lambda deployment

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  PetStoreMVC:
    Type: AWS::Serverless::Function
    Properties:
#      AutoPublishAlias: bcn
      FunctionName: uppercase
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      SnapStart:
        ApplyOn: PublishedVersions
      CodeUri: .
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          MAIN_CLASS: example.FunctionConfiguration

      
```

**Sample**
I build project 

```
mvn clean package
```
create folder events

and  file event.json
```
"Tom"
```

then run

```
sam local invoke PetStoreMVC --event events/event.json
```

and got error

```
Mounting C:\Users\vsvdev\Desktop\function-sample-aws as /var/task:ro,delegated, inside runtime container
START RequestId: 18e0e11a-a14e-4961-a383-2abfd37009dc Version: $LATEST
Class not found: org.springframework.cloud.function.adapter.aws.FunctionInvoker: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: org.springframework.cloud.function.adapter.aws.FunctionInvoker
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)

END RequestId: 913bad25-6b9f-46d8-855d-aae1ca211273
REPORT RequestId: 913bad25-6b9f-46d8-855d-aae1ca211273  Init Duration: 0.14 ms  Duration: 406.05 ms     Billed Duration: 407 ms Memory Size: 1024 MB    Max Memory Used: 1024 MB
{"errorMessage": "Class not found: org.springframework.cloud.function.adapter.aws.FunctionInvoker", "errorType": "java.lang.ClassNotFoundException"}


```
