### ISSUE TITLE
Slow cold starts

### ISSUE THREAD

**Issue by newalopez** [spring-cloud/spring-cloud-function#132]
Hi there, I'm using the project, with the api gateway for AWS, still Api gateway only admits 29,000 ms as maximum delay, but I'm getting loading times over 30s, for a simple 5 classes project:

https://gist.github.com/newalopez/7c11acc11ba730891e8f470b812f8271

Is there something I could add to make it faster?

(the warmed up calls are fast, 20ms).

.yml:
```
spring:
  profiles:
    active: "prod"
  main:
    banner-mode: "off"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      temp:
        use_jdbc_metadata_defaults: false

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://xxx.cluster-xxx.us-west-2.rds.amazonaws.com:3306/xxxx
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 1
      initial-size: 1
      min-idle: 1
    jmx-enabled: false
  ```
