### ISSUE TITLE
Able to invoke function directly but unable to curl the exposed POST http endpoint

### ISSUE THREAD

**Issue by aravindbargurhiriyannaiah** [spring-cloud/spring-cloud-function#241]
Hello,

While I am able to run https://github.com/mbsambangi/aws-java-spring-cloud-function-demo as is (by invoking the function), it isn't working when I introduce a http event to the serverless.yml.

The modified serverless.yml file is below
```
service: sls-aws-java-spring-cloud-function-demo
provider:
  name: aws
  runtime: java8
  timeout: 10
package:
  artifact: target/aws-java-spring-cloud-function-demo-0.0.1-SNAPSHOT-aws.jar
functions:
  members:
    handler: com.healthfirst.memberfunction.AwsLambdaHandler
    environment:
      FUNCTION_NAME: members
    events:
      - http: 
          path: /
          method: POST
```

This is happening with other functions too. Am I missing something or is it a bug?

The error when I try to curl it
```
curl -X POST https://xxxxxxxx.execute-api.yyyyyy.amazonaws.com/dev/ -H "Content-type: application/json" --data '{"memberId":"1234567890"}' 

{"message": "Internal server error"}
```
