### ISSUE TITLE
"Wiretap" or "export" feature

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#26]
Basic idea: user declares (somehow) an interest in "exporting" items of a given POJO type `Foo` (say), and framework generates 2 beans: one is a `Consumer<Foo>` and the other is a `Supplier<Flux<Foo>>`. The framework already automatically adds the `Supplier` to the `FunctionCatalog`, so it can be used to send `Foos` to an external stream or HTTP client. The `Consumer` is implemented in such a way that it pushes each `Foo` into the `Flux` stream created by the `Supplier`.

I implemented it here as `@EnableWiretap` but the name could be changed: https://github.com/dsyer/petflix/blob/master/videos/src/main/java/com/example/VideoApplication.java#L15.

**Comment by dsyer** [comment]
I suppose the user might want multiple exports for objects of the same type, so `@EnableWiretap(Foo.class)` is not enough for the general case. There's a naming problem anyway (the bean names need to be customizable a bit in general). So maybe `@EnableWiretap(@Wiretap(type=Foo.class, name="foos"))` would work better, or as an alternative.

**Comment by markfisher** [comment]
interesting idea - I wonder if we want to support this via properties in a way similar to other currently configurable functions. For example, we currently have `compile`, `import`, etc:

````
spring:
  cloud:
    function:
      compile:
        uppercase:
          lambda: s->s.toUpperCase()
          inputType: String
          outputType: String
        hello:
          type: supplier
          lambda: ()->"hello"
          outputType: String
      import:
        lowercase:
          location: file:///tmp/function-registry/functions/lowercase.fun
      scan:
        packages: fun1, fun2
      inject:
        greeter:
          greeting: howdy
````

So perhaps we could add `export.<name>`, and we could even use SpEL for the "definition" thereby supporting `@bean.whatever()` syntax.
