### ISSUE TITLE
Hoxton.SR9 + functions + reactive stream compatibility issue

### ISSUE THREAD

**Issue by tdanylchuk** [spring-cloud/spring-cloud-function#608]
I have a reactive application with spring cloud stream kafka consumer configured.
My consumer bean looks like:
```
public class MyConsumer implements Consumer<Flux<MyObject>> {
    @Override
    public void accept(Flux<MyObject> rewardsFlux) {
        rewardsFlux.doOnNext(event -> log.debug("Consumed reward event - {}.", event))
                .subscribe();
    }
}
```

and its configs (plus destination and kafka broker config)
```
spring:
    cloud.stream:
        bindings:
            my-binding:
                group: ${spring.application.name}
                content-type: application/json
        function:
            bindings:
                myConsumer-in-0: my-binding
            definition: myConsumer
```

So this setup worked alright on version `Hoxton.SR8` but stop working in the right way after bumping dependencies to the latest versions. The problem is that my object contains null fields after de-serialization. I dug a bit deeper and found that this commit https://github.com/spring-cloud/spring-cloud-function/commit/222aac77ccbcc9dd9018101f131fdf93a0f466f0 is actually breaking expected behavior since its checking raw type with actual type 
rawType = `MyCustomObject`
type = `Flux<MyCustomObject>`
and since they are different it puts a deserialization hint (as a view) to the converter.

Please note that if **spring-cloud-function-context** dependency would be downgraded  3.0.11.RELEASE -> 3.0.10.RELEASE. everything will work as expected.
