### ISSUE TITLE
Kafka Topic stream consumer not getting previous messages

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-function#80]
I apologize in advance if this is a newbie question I would've asked on Stackoverflow but I think there isn't dedicated Spring Cloud Function support over there yet.

**Scenario in Spring Cloud Stream Apps:**
App1 sends messages to a topic - App2 offline
App2 starts and processes all the messages sent to the topic by App1 while App2 was offline.

**Scenario in Spring Cloud Function Apps:**
App1 (supplier) sends messages to a topic - App2 offline
App2 (consumer) doesn't get the previous messages, only the ones produced while App1 and App2 are up at the same time.

What's the explanation of this different behaviour?

**Comment by dsyer** [comment]
I don't think there should be any difference as long as the apps are configured the same way. The Kafka consumer index is stored according to the policy set by the destination "group" in the Spring Cloud Stream configuration. It might be good to look at that and try and understand why it is different in your case.

**Comment by codependent** [comment]
Hi @dsyer, this was my previous cfg:

**supplier:**
```
spring:
  application:
    name: supplier
  cloud:
    stream:
      bindings:
        output:
          destination: raw-events
```

**consumer:**
spring:
  cloud:
    function:
      scan:
        packages: com.codependent.serverless.processor 
    stream:
      bindings:
        input:
          destination: raw-events
        output: 
          destination: processed-events

As soon as I added a group name in the consumer input configuration I started to get the messages that had been previously produced by the consumer. 

```
spring:
  cloud:
    function:
      scan:
        packages: com.codependent.serverless.processor 
    stream:
      bindings:
        input:
          group: stream-processors
          destination: raw-events
        output: 
          destination: processed-events
```
Would you be so kind of explaining why it doesn't work with the default group and it's necessary to add a specific group name?
