### ISSUE TITLE
Unable to use routing feature with AWS custom runtime

### ISSUE THREAD

**Issue by yujinchoi-94** [spring-cloud/spring-cloud-function#829]
**Describe the bug**
`Spring Cloud Function :  3.2.2`

I've been developing AWS lambda application with Spring Cloud Function and Spring native.
I was trying to add more function and use [aws routing](https://docs.spring.io/spring-cloud-function/docs/3.2.2/reference/html/aws.html#_aws_function_routing) feature.

However, when I implemented `MessageRoutingCallback` strategy, the application couldn't find the default function(RoutingFunction).

When I don't use custom runtime, it worked as expected (used RoutingFunction)
I found this log from worked one.
```
2022-03-15 07:56:16.946  INFO 16 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : More then one function is available in FunctionCatalog. [appRouter, mainRouter, functionRouter] Will default to RoutingFunction, Expecting 'spring.cloud.function.definition' or 'spring.cloud.function.routing-expression' as Message headers. If invocation is over API Gateway, Message headers can be provided as HTTP headers.
```

On the other hand, when I used custom runtime, I couldn't find any messages from`FunctionInvoker`.
Thus, I explicitly set `spspring.cloud.function.definition` to `functionRouter` as it is the default function when there is more than one function, then routing feature worked.

What I am wondering is whether it is intended or not that routing feature is disabled when we use custom runtime.
If it is intended, I think more document is needed. 
Also, I want to know any alternative ways to use routing feature when using custom runtime. 
(Is it okay to use explicitly set FunctionRouter as the default function?)

**Sample**
https://github.com/yujinchoi-94/custom-routing-demo

**Comment by olegz** [comment]
I am not sure I exactly follow as it appears that something is missing from your explanation.

First, the `FunctionInvoker` is not used with Custom Runtime due to the fact that `FunctionInvoker` is a handler for an AWS provided runtime (which is not under our control). That is why when you deploy you specify `FunctionInvoker::handleRequest` as a handler. 
But for the Custom Runtime, the implementation of which is under our control the _handler_ is the actual function which you _must_ specify when you deploy. Specifying `spring.cloud.function.definition` is a bit meaningless with Custom Runtime, hence my questions:

- with custom runtime what do you specify as a handler?
- where exactly you specify `spring.cloud.function.definition` in the context of Custom Runtime?

**Comment by yujinchoi-94** [comment]
Hi,
the code below is what I've configured and you can also find the details including actual code here https://github.com/yujinchoi-94/custom-routing-demo

### sam build file
```yaml
Resources:
  CustomRuntimeRoutingDemo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: /Users/a1101580/IdeaProjects/custom-runtime-routing-demo/target/custom-runtime-routing-demo-0.0.1-SNAPSHOT-native-zip.zip
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: provided
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          logging_level_root: DEBUG
          spring_cloud_function_definition: functionRouter # I have to explicitly set this property. Without this, the app was unable to find the default function to run
          server_port: 8090
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```

### Application code to determine function
```java
@SpringBootApplication
public class CustomRuntimeRoutingDemoApplication {
	public static void main(String[] args) {
		SpringApplication.run(CustomRuntimeRoutingDemoApplication.class, args);
	}

	@Bean
	public MessageRoutingCallback customRouter() {
		return new MessageRoutingCallback() {
			@Override
			public FunctionRoutingResult routingResult(Message<?> message) {
				return new FunctionRoutingResult((String)message.getHeaders().get("Func-Name"));
			}
		};
	}
}
```

However, https://github.com/spring-projects-experimental/spring-native/issues/1529 this issue is similar to what I've been experienced. 
It also uses custom runtime and having issue with using multiple routing.

Is it impossible to use multi routing feature with custom runtime?
