### ISSUE TITLE
Snapstart Integration 

### ISSUE THREAD

**Issue by nbenjamin** [spring-cloud/spring-cloud-function#967]
Currently we are using spring cloud function for AWS lambda. Recently AWS introduced [SnapStart](https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html) to improve the `cold start` time which helps tremendously the cold start time. As a best practice will have to re-establish any network connection in the function, [CraC](https://github.com/CRaC/org.crac) provide [afterRestore](https://javadoc.io/static/io.github.crac/org-crac/0.1.3/org/crac/Resource.html#afterRestore-org.crac.Context-) and [beforeCheckpoint](https://javadoc.io/static/io.github.crac/org-crac/0.1.3/org/crac/Resource.html#beforeCheckpoint-org.crac.Context-). 

So wanted to check if there is any integration possibility to make use of this in spring cloud function

**Comment by olegz** [comment]
Basically it works. @msailes of AWS and I have tried it and it just works. 
Yes, there may be a need to deal with some resources, but that is specific to a particular application. However it could be as simple as stopping/starting application context in the respective `beforeCheckpoint` and `afterRestore`  providing that such resource implements Spring's `Lifecycle`, which network resources provided by Spring typically do. So yes in the future we can provide such implementation and probably at the level of Spring-core/boot. But it is too early to do anything at this point, so i suggest provide your own implementation of Resource and distribute it with your app for now where you would stop/start AC. For apps that do not deal with network resources of file handlers there is nothing that needs to be done

**Comment by bala-cbt** [comment]
Dear Oleg,
    We have been trying to integrate Spring Cloud function with AWS Snapstart to improve cold start times. There has been a significant improvement in the start times. However, we have been facing an issue where the first request to the function call fails (with a 500 status code). All subsequent function calls work fine. We have deployed our functions behind an AWS API Gateway. The functions work fine when we do not use Snapstart (but has longer cold start times). It would be very helpful if you can share some thoughts/advice that can help us troubleshoot this issue. Thank you.

**Comment by msailes** [comment]
Hi @bala-cbt, that isn't much information. Is there anything more you can share? Errors? Are you writing any runtime hooks? Do you have a public example?

**Comment by bala-cbt** [comment]
Hi @msailes 
Thank you for your response. We are using the serverless framework to deploy the spring cloud functions on AWS Lambda. We are not using any runtime hooks.
A sample function definition from the serverless.yml is as below:

```
functions:
  inviteUser:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    events:
      - httpApi:
          path: /authenticated/users/invite
          method: post
          authorizer: customAuthorizer
    environment:
      FUNCTION_NAME: inviteUser
      SPRING_CLOUD_FUNCTION_DEFINITION: inviteUser
    runtime: java11
    snapStart: true
    memorySize: 4096
    role: arn:aws:iam::xxxxxx:role/xxxxxx
    package:
      artifact: target/app-0.0.1-SNAPSHOT-aws.jar
```
When we access the function for the first time, we get a 500 status code (Internal Server error). This is intermittent and we currently do not see any fixed pattern. Subsequent requests to the function are successful.
This is what we have from the CloudWatch logs.

For a failed request, there is only one line in the logs
      RESTORE_START Runtime Version: java:11.v15 Runtime Version ARN: arn:aws:lambda:eu-west-1::runtime:xxxxxxx

and we do not see any RESTORE_REPORT or Restore Duration.

For a successful request, we see
RESTORE_START Runtime Version: java:11.v15 Runtime Version ARN: arn:aws:lambda:eu-west-1::runtime:xxxxx
RESTORE_REPORT Restore Duration: 1547.11 ms
and the start of the request and the application logs

Could this issue be due to incorrect restoration of the snapshot? Is there any way we can troubleshoot this?  I will try to create and share a public example in a couple of days.
